### ISSUE TITLE
Dev, testing questions

### ISSUE THREAD

**Issue by justincormack** [mhausenblas/aws-container-security-survey-2020#1]
I am really interested in dev environments and processes, would love questions along the lines of

a. What development environment do you use locally - do you use kub for dev or not? (eg Docker desktop, minikube etc)
b. do you use cloud for dev, and does the dev env match production or is it different (eg do you use k8s for test and prod)
c. What about CI, do you do CI with k8s or not? Where do you run CI (eg in circle, actions, or on jenkins in AWS or what)

**Comment by mhausenblas** [comment]
Thanks a lot for the suggestion @justincormack! I'm a little concerned about the scoping here since I want to keep the number of questions small and focused on security. Including the above mentioned questions properly would likely result in a suboptimal survey. 

I'm really on the fence here since I think it would be an awesome survey in itself. Shall we jump on a call to hash this out, talking about potentially other options since I really, really, really would like to see a DX survey for Kubernetes (independent of AWS). WDYT?

**Comment by justincormack** [comment]
Ah yes, sorry I didnt read the full survey title... makes sense. I have been drafting some container DX questions, I think we may do a survey, but happy to add more stuff.
